# Generated by Django 5.2.13 on 2026-06-17 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0011_mlopsconfig_trainingjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SOFT_DELETE', 'Soft Delete'), ('VALIDATE', 'Validate'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('STATUS_CHANGE', 'Status Change'), ('VERSION_CREATE', 'Version Create'), ('RESTORE', 'Restore'), ('REVIEW', 'Review'), ('RISK_ACCEPT', 'Risk Accept'), ('RISK_MITIGATE', 'Risk Mitigate'), ('EXPORT', 'Export')], max_length=32)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('performed_by', models.CharField(max_length=150)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('session_id', models.CharField(blank=True, default='', max_length=128)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='compliance__entity__3a498a_idx'), models.Index(fields=['performed_by', '-performed_at'], name='compliance__perform_0837f2_idx'), models.Index(fields=['action', '-performed_at'], name='compliance__action_f1e86d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('READY', 'Audit Ready'), ('PARTIAL', 'Partially Ready'), ('NOT_READY', 'Not Ready')], default='NOT_READY', max_length=16)),
                ('coverage_ok', models.BooleanField(default=False)),
                ('quality_ok', models.BooleanField(default=False)),
                ('no_expired', models.BooleanField(default=False)),
                ('no_critical_gaps', models.BooleanField(default=False)),
                ('low_duplication', models.BooleanField(default=False)),
                ('avg_quality_score', models.FloatField(default=0.0)),
                ('duplication_rate', models.FloatField(default=0.0)),
                ('expired_count', models.PositiveIntegerField(default=0)),
                ('critical_gap_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('norme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_readiness', to='api.norme')),
            ],
            options={
                'verbose_name': 'Audit Readiness',
            },
        ),
        migrations.CreateModel(
            name='ComplianceCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rules', models.PositiveIntegerField(default=0)),
                ('covered_rules', models.PositiveIntegerField(default=0)),
                ('critical_rules', models.PositiveIntegerField(default=0)),
                ('critical_covered', models.PositiveIntegerField(default=0)),
                ('coverage_pct', models.FloatField(default=0.0)),
                ('critical_pct', models.FloatField(default=0.0)),
                ('uncovered_rules', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('norme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='api.norme')),
            ],
            options={
                'verbose_name': 'Compliance Coverage',
            },
        ),
        migrations.CreateModel(
            name='ComplianceMaturity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturity_score', models.FloatField(default=0.0)),
                ('maturity_level', models.CharField(choices=[('INITIAL', 'Initial (0-40)'), ('DEVELOPING', 'Developing (41-60)'), ('MANAGED', 'Managed (61-80)'), ('OPTIMIZED', 'Optimized (81-100)')], default='INITIAL', max_length=16)),
                ('coverage_score', models.FloatField(default=0.0)),
                ('quality_score', models.FloatField(default=0.0)),
                ('readiness_score', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('norme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maturity', to='api.norme')),
            ],
            options={
                'verbose_name': 'Compliance Maturity',
            },
        ),
        migrations.CreateModel(
            name='CriticalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_critical', models.BooleanField(default=True)),
                ('rationale', models.TextField(blank=True)),
                ('frameworks', models.JSONField(blank=True, default=list)),
                ('control_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='critical_control', to='api.rule')),
            ],
            options={
                'verbose_name': 'Critical Control',
            },
        ),
        migrations.CreateModel(
            name='EvidenceQualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.FloatField(default=0.0)),
                ('quality_level', models.CharField(choices=[('EXCELLENT', 'Excellent (90-100)'), ('GOOD', 'Good (70-89)'), ('WARNING', 'Warning (50-69)'), ('POOR', 'Poor (0-49)')], default='POOR', max_length=16)),
                ('has_evidence_text', models.BooleanField(default=False)),
                ('has_document', models.BooleanField(default=False)),
                ('has_human_review', models.BooleanField(default=False)),
                ('is_not_duplicate', models.BooleanField(default=True)),
                ('has_recent_review', models.BooleanField(default=False)),
                ('has_comment', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_score', to='api.ruletrainingsample')),
            ],
            options={
                'verbose_name': 'Evidence Quality Score',
            },
        ),
        migrations.CreateModel(
            name='PeriodicReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('BIANNUAL', 'Bi-annual'), ('ANNUAL', 'Annual')], default='ANNUAL', max_length=16)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('CURRENT', 'Current'), ('NEEDS_REVIEW', 'Needs Review'), ('OVERDUE', 'Overdue')], default='CURRENT', max_length=16)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedule', to='api.rule')),
            ],
            options={
                'verbose_name': 'Periodic Review',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('changed_by', models.CharField(max_length=150)),
                ('change_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.document')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='compliance.documentversion')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='EvidenceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('changed_by', models.CharField(max_length=150)),
                ('change_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.ruletrainingsample')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='compliance.evidenceversion')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('evidence', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=12)),
                ('likelihood', models.PositiveSmallIntegerField(default=3)),
                ('impact', models.PositiveSmallIntegerField(default=3)),
                ('risk_score', models.FloatField(default=9.0)),
                ('owner', models.CharField(blank=True, max_length=150)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MITIGATED', 'Mitigated'), ('ACCEPTED', 'Accepted'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='api.rule')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='api.norme')),
            ],
            options={
                'ordering': ['-risk_score', '-created_at'],
                'indexes': [models.Index(fields=['standard', 'status'], name='compliance__standar_abf27a_idx'), models.Index(fields=['-risk_score'], name='compliance__risk_sc_b5a44f_idx')],
            },
        ),
    ]
