# Generated by Django 5.2.13 on 2026-04-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Norme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('employee_username', models.CharField(max_length=150)),
                ('employee_department', models.CharField(blank=True, max_length=120)),
                ('teamlead_username', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('norme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='api.norme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('norme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.norme')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamlead_username', models.CharField(max_length=150)),
                ('evidence_text', models.TextField(blank=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='validations/%Y/%m/%d/')),
                ('is_valid', models.BooleanField(null=True)),
                ('comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='api.document')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations', to='api.rule')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('document', 'rule')},
            },
        ),
    ]
