# Generated by Django 5.2.13 on 2026-04-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trainingsample_standard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingsample',
            options={'ordering': ['-created_at'], 'verbose_name': 'Training Dataset', 'verbose_name_plural': 'Training Dataset'},
        ),
        migrations.RenameIndex(
            model_name='trainingsample',
            new_name='api_trainin_standar_bee9cd_idx',
            old_name='api_training_standard_idx',
        ),
    ]
