# Generated by Django on 2026-05-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_trainingsample_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], default='HIGH', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='condition',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='action',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
