# Generated by Django 5.2.13 on 2026-05-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trainingsample_extended'),
        ('api', '0006_training_sample_metrics'),
    ]

    operations = [
    ]
