# Generated by Django 5.2.13 on 2026-05-22 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20260520_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleTrainingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_title', models.CharField(blank=True, default='', max_length=255)),
                ('rule_description', models.TextField(blank=True, default='')),
                ('document_text', models.TextField(blank=True, default='')),
                ('evidence_text', models.TextField(blank=True, default='')),
                ('reviewer_comment', models.TextField(blank=True, default='')),
                ('recommendation', models.CharField(blank=True, default='', max_length=255)),
                ('semantic_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('label', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rule Training Sample',
                'verbose_name_plural': 'Rule Training Samples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_approved', 'Auto Approved')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='rule',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], default='HIGH', max_length=12),
        ),
        migrations.AlterField(
            model_name='trainingsample',
            name='features',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='trainingsample',
            index=models.Index(fields=['norm_id', 'label'], name='api_trainin_norm_id_c3ec2e_idx'),
        ),
        migrations.AddField(
            model_name='ruletrainingsample',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_training_samples', to='api.document'),
        ),
        migrations.AddField(
            model_name='ruletrainingsample',
            name='norm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.norme'),
        ),
        migrations.AddField(
            model_name='ruletrainingsample',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rule'),
        ),
        migrations.AddIndex(
            model_name='ruletrainingsample',
            index=models.Index(fields=['norm', 'rule'], name='api_ruletra_norm_id_e699de_idx'),
        ),
        migrations.AddIndex(
            model_name='ruletrainingsample',
            index=models.Index(fields=['document', 'rule'], name='api_ruletra_documen_9efb5d_idx'),
        ),
        migrations.AddIndex(
            model_name='ruletrainingsample',
            index=models.Index(fields=['-created_at'], name='api_ruletra_created_6fe218_idx'),
        ),
    ]
