# Generated by Django 5.2.13 on 2026-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_training_sample_aggregates'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='document',
            name='decision_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='final_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_approved', 'Auto Approved')], default='pending', help_text='Explicit final decision from the team lead.', max_length=16),
        ),
        migrations.AddField(
            model_name='document',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='review_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewer_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ruletrainingsample',
            name='final_document_decision',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='trainingsample',
            name='decision_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainingsample',
            name='final_decision',
            field=models.CharField(blank=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='validation',
            name='decision_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='validation',
            name='reviewer_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trainingsample',
            name='rule_results_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
