# Generated by Django 5.2.13 on 2026-06-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_document_approved_at_document_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLOpsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=50, unique=True)),
                ('last_trained_at', models.DateTimeField(blank=True, null=True)),
                ('last_trained_doc_count', models.PositiveIntegerField(default=0)),
                ('current_model_version', models.CharField(blank=True, default='', max_length=100)),
                ('retraining_threshold', models.PositiveIntegerField(default=1)),
                ('auto_trigger_enabled', models.BooleanField(default=False)),
                ('last_f1_score', models.FloatField(default=0.0)),
                ('last_drift_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['standard'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(default='ISO9001', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('documents_count', models.PositiveIntegerField(default=0)),
                ('new_docs_since', models.PositiveIntegerField(default=0)),
                ('drift_score', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('precision_score', models.FloatField(default=0.0)),
                ('recall_score', models.FloatField(default=0.0)),
                ('avg_similarity', models.FloatField(default=0.0)),
                ('model_version', models.CharField(blank=True, default='', max_length=100)),
                ('jenkins_build_id', models.CharField(blank=True, default='', max_length=100)),
                ('jenkins_url', models.URLField(blank=True, default='')),
                ('triggered_by', models.CharField(blank=True, default='', max_length=150)),
                ('drift_report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_time', '-created_at'],
                'indexes': [models.Index(fields=['status', '-start_time'], name='api_trainin_status_57c35a_idx'), models.Index(fields=['standard', '-start_time'], name='api_trainin_standar_8879e2_idx')],
            },
        ),
    ]
