# Generated by Django 5.2.15 on 2026-06-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_documenttrainingsample_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documenttrainingsample',
            new_name='api_documen_standar_63ca70_idx',
            old_name='api_document_standard_4f81a0_idx',
        ),
        migrations.RenameIndex(
            model_name='documenttrainingsample',
            new_name='api_documen_label_e6a8ef_idx',
            old_name='api_document_label_7b1d9c_idx',
        ),
    ]
