# Generated by Django 5.2.15 on 2026-06-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_trainingjob_accuracy_duration_mlopsconfig_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlopsconfig',
            name='retraining_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='dataset_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
