# Generated by Django 5.2.15 on 2026-07-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_document_encryption_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='encrypted_key_id',
            field=models.CharField(blank=True, default='', help_text='Identifier of the key used (e.g. env_key, kms_key_v2).', max_length=64, verbose_name='Encryption key ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='encryption_iv',
            field=models.CharField(blank=True, default='', help_text='Base64-encoded 12-byte GCM nonce (informational).', max_length=24, verbose_name='Encryption IV (nonce)'),
        ),
    ]
