# Generated by Django 5.2.13 on 2026-06-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_username', models.CharField(db_index=True, max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('DOCUMENT_SUBMITTED', 'Document Submitted'), ('DOCUMENT_APPROVED', 'Document Approved'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('VALIDATION_REQUIRED', 'Validation Required'), ('AUDIT_DEADLINE', 'Audit Deadline Approaching'), ('COMPLIANCE_GAP', 'Compliance Gap Detected'), ('CRITICAL_RISK', 'Critical Risk Detected'), ('ML_DRIFT', 'ML Model Drift Detected'), ('REVIEW_OVERDUE', 'Review Overdue'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=32)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=12)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=64)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_username', '-created_at'], name='notificatio_recipie_a39156_idx'), models.Index(fields=['recipient_username', 'is_read', '-created_at'], name='notificatio_recipie_472a66_idx')],
            },
        ),
    ]
