# ==========================
# SonarQube Project
# ==========================
sonar.projectKey=enterprise-iso-compliance
sonar.projectName=Enterprise ISO Compliance Platform
sonar.projectVersion=1.0

# SonarQube Server
sonar.host.url=http://localhost:9000

# Encodage
sonar.sourceEncoding=UTF-8

# Code à analyser
sonar.sources=backend,frontend/src

# Version Python
sonar.python.version=3.11

# Exclusions
sonar.exclusions=\
**/.venv/**,\
**/venv/**,\
**/node_modules/**,\
**/__pycache__/**,\
**/migrations/**,\
**/build/**,\
**/dist/**,\
**/static/**,\
**/media/**,\
**/*.min.js,\
**/*.css.map

# Tests (optionnel)
sonar.tests=backend
sonar.test.inclusions=**/tests.py,**/test_*.py