"""
Advanced feature engineering for compliance documents.

Extracts and normalizes features from documents:
- has_version, has_author, has_date, has_history
- document_length, word_count, avg_word_length
- Special characters, tables, images
- Similarity scores, readability metrics
"""

import re
import json
from typing import Dict, Tuple
from collections import Counter
import logging

logger = logging.getLogger(__name__)


class FeatureExtractor:
    """Extract advanced features from document text."""
    
    # Patterns for feature detection
    VERSION_PATTERNS = [
        r'v(?:ersion)?\s*\d+\.\d+',
        r'rev(?:ision)?\s*(?:no\.?|number)?\s*\d+',
        r'v\d+(?:\.\d+)*',
    ]
    
    AUTHOR_PATTERNS = [
        r'(?:author|written by|created by)[\s:]+([a-z\s\.]+)',
        r'(?:prepared by|generated by)[\s:]+([a-z\s\.]+)',
    ]
    
    DATE_PATTERNS = [
        r'\d{1,2}[/-]\d{1,2}[/-]\d{4}',
        r'\d{4}[/-]\d{1,2}[/-]\d{1,2}',
        r'(?:january|february|march|april|may|june|july|august|september|october|november|december)\s+\d{1,2},?\s+\d{4}',
    ]
    
    HISTORY_PATTERNS = [
        r'(?:version history|change history|revision history|changelog)',
        r'(?:v\d+\.\d+\s*\|\s*\d{1,2}[/-]\d{1,2}[/-]\d{4}){2,}',  # Multiple version entries
    ]
    
    @staticmethod
    def has_feature(text: str, patterns: list) -> bool:
        """Check if text contains any pattern from the list."""
        if not text:
            return False
        text_lower = text.lower()
        for pattern in patterns:
            if re.search(pattern, text_lower, re.IGNORECASE):
                return True
        return False
    
    @classmethod
    def extract_all(cls, text: str) -> Dict[str, any]:
        """Extract all features from document text."""
        if not text:
            text = ''
        
        # Basic metrics
        word_list = text.split()
        word_count = len(word_list)
        document_length = len(text)
        avg_word_length = document_length / max(word_count, 1)
        
        # Character patterns
        uppercase_ratio = sum(1 for c in text if c.isupper()) / max(document_length, 1)
        special_char_count = sum(1 for c in text if not c.isalnum() and not c.isspace())
        
        # Structure
        paragraph_count = len([p for p in text.split('\n\n') if p.strip()])
        line_count = len(text.split('\n'))
        
        # Tables and lists (heuristic)
        table_like_count = text.count('|') // 2  # Rough estimate
        list_items = len(re.findall(r'^[\s]*[-•*+]\s', text, re.MULTILINE))
        
        # Feature detection
        has_version = cls.has_feature(text, cls.VERSION_PATTERNS)
        has_author = cls.has_feature(text, cls.AUTHOR_PATTERNS)
        has_date = cls.has_feature(text, cls.DATE_PATTERNS)
        has_history = cls.has_feature(text, cls.HISTORY_PATTERNS)
        
        # Headers/sectioning
        header_count = len(re.findall(r'^#{1,6}\s', text, re.MULTILINE))  # Markdown style
        header_count += len(re.findall(r'^\d+\.\s+[A-Z]', text, re.MULTILINE))  # Numbered sections
        
        # Readability approximation (Flesch-Kincaid inspired)
        sentences = len(re.split(r'[.!?]+', text))
        avg_words_per_sentence = word_count / max(sentences, 1)
        
        # Code/technical content
        code_block_count = len(re.findall(r'```|<pre>|<code>', text, re.IGNORECASE))
        
        return {
            # Basic metrics
            'document_length': document_length,
            'word_count': word_count,
            'avg_word_length': round(avg_word_length, 2),
            'paragraph_count': paragraph_count,
            'line_count': line_count,
            'sentence_count': sentences,
            'avg_words_per_sentence': round(avg_words_per_sentence, 2),
            
            # Character analysis
            'uppercase_ratio': round(uppercase_ratio, 2),
            'special_char_count': special_char_count,
            
            # Structure
            'table_like_count': table_like_count,
            'list_items': list_items,
            'header_count': header_count,
            'code_block_count': code_block_count,
            
            # Feature presence (binary)
            'has_version': int(has_version),
            'has_author': int(has_author),
            'has_date': int(has_date),
            'has_history': int(has_history),
            
            # Readability
            'is_structured': int(header_count > 0 or list_items > 0),
        }


def normalize_features(raw_features: Dict[str, any]) -> Dict[str, float]:
    """
    Normalize features to [0, 1] range for ML models.
    
    Uses manual min-max normalization based on reasonable bounds.
    """
    normalized = {}
    
    # Define bounds for normalization (adjust based on your corpus)
    bounds = {
        'document_length': (0, 50000),  # 0-50KB
        'word_count': (0, 10000),
        'avg_word_length': (0, 20),
        'paragraph_count': (0, 200),
        'line_count': (0, 1000),
        'sentence_count': (0, 500),
        'avg_words_per_sentence': (0, 50),
        'uppercase_ratio': (0, 1),
        'special_char_count': (0, 5000),
        'table_like_count': (0, 100),
        'list_items': (0, 200),
        'header_count': (0, 50),
        'code_block_count': (0, 50),
        'has_version': (0, 1),
        'has_author': (0, 1),
        'has_date': (0, 1),
        'has_history': (0, 1),
        'is_structured': (0, 1),
    }
    
    for key, value in raw_features.items():
        if key in bounds:
            min_val, max_val = bounds[key]
            if max_val > min_val:
                normalized[key] = (value - min_val) / (max_val - min_val)
                normalized[key] = max(0.0, min(1.0, normalized[key]))  # Clamp to [0, 1]
            else:
                normalized[key] = 0.0
        else:
            # Pass through unknown features
            normalized[key] = value
    
    return normalized


def build_feature_vector_from_text(
    document_text: str,
    rule_text: str = '',
    evidence_text: str = ''
) -> Dict[str, any]:
    """
    Build complete feature vector for training sample.
    
    Combines:
    - Document text features
    - Rule text presence
    - Evidence text analysis
    """
    if not document_text:
        document_text = ''
    
    # Extract document features
    doc_features = FeatureExtractor.extract_all(document_text)
    
    # Evidence analysis
    evidence_features = {
        'evidence_present': int(bool(evidence_text)),
        'evidence_length': len(evidence_text) if evidence_text else 0,
        'has_evidence_url': int('http' in (evidence_text or '').lower()),
        'has_evidence_page_ref': int('page' in (evidence_text or '').lower()),
    }
    
    # Rule presence in document
    rule_features = {}
    if rule_text and document_text:
        rule_words = set(rule_text.lower().split())
        doc_words = set(document_text.lower().split())
        overlap = len(rule_words & doc_words)
        rule_features['rule_word_overlap'] = overlap
        rule_features['rule_match_ratio'] = round(overlap / max(len(rule_words), 1), 2)
    else:
        rule_features['rule_word_overlap'] = 0
        rule_features['rule_match_ratio'] = 0.0
    
    # Combine all features
    all_features = {**doc_features, **evidence_features, **rule_features}
    
    # Normalize
    normalized_features = normalize_features(all_features)
    
    return normalized_features


# Export public API
__all__ = [
    'FeatureExtractor',
    'normalize_features',
    'build_feature_vector_from_text',
]
