# Generated by Django 5.2.15 on 2026-07-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentsecurityanalysis',
            new_name='security_do_risk_le_46e0fe_idx',
            old_name='security_do_risk_le_idx',
        ),
        migrations.RenameIndex(
            model_name='documentsecurityanalysis',
            new_name='security_do_confide_5276b3_idx',
            old_name='security_do_conf_le_idx',
        ),
        migrations.RenameIndex(
            model_name='documentsecurityanalysis',
            new_name='security_do_gdpr_st_cddd6c_idx',
            old_name='security_do_gdpr_st_idx',
        ),
    ]
