# Generated by Django 5.2.13 on 2026-04-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='keycloak_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
