# Generated by Django 4.2.11 on 2026-04-09 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0002_alter_userprofile_keycloak_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'User Created'), ('UPDATE', 'User Updated'), ('DELETE', 'User Deleted'), ('LOGIN', 'User Logged In'), ('PASSWORD_CHANGE', 'Password Changed'), ('ROLE_CHANGE', 'Role Changed'), ('DEPARTMENT_CHANGE', 'Department Changed')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='rbac_auditl_user_id_cf611c_idx'), models.Index(fields=['action', '-timestamp'], name='rbac_auditl_action_d6cbcb_idx')],
            },
        ),
    ]
