# Generated by Django 5.2.13 on 2026-04-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
